### PR TITLE
Bump MongoDB driver to 2.28.0

### PR DESCRIPTION
**Pull request by miszu**
Thanks a lot for maintaining the library, appreciate it!

I bumped the driver to the latest v2.28.0 (https://github.com/mongodb/mongo-csharp-driver/releases/tag/v2.28.0). I was not able to run the tests locally on my Mac due to missing NET4.7, so I spent some time updating the setup. Some of these changes are a bit opinionated, so I'll totally understand if you'd prefer to skip some changes (feel free to give feedback or make any edits yourself).

- changed target framework for **test** projects to net8
- removed App.config from CoreIntegrationTests, as it was not used there
- in IntegrationTests, I couldn't get the App.config to work, so I migrated to appsettings.json
- simplified IntegrationTests.csproj by removing not needed references

**Green tests 🎉**
Screenshot 2024-08-05 at 12 15 11

### CODE REVIEW

**Comment by madsquist** [comment]
@alexandre-spieser Could you please merge this PR? 👍 

This is **important** because the guys at MongoDB screwed up:
https://www.mongodb.com/community/forums/t/net-c-driver-strong-naming/291649

People who use this package, will not be able to upgrade their Mongo Driver packages to any version >= 2.27 if you don't upgrade as well.

**Comment by alexandre-spieser** [comment]
Thanks the initiative and sorry for the delayed response.
That PR removed an old target framework compatibility which I'd like to keep for a bit longer for folks running on legacy stuff.
I've therefore kept the changes to a minimum in that PR https://github.com/alexandre-spieser/mongodb-generic-repository/pull/61
1.6.2 is pushed and should address the issues you're facing.
https://www.nuget.org/packages/MongoDbGenericRepository

**Comment by madsquist** [comment]
@alexandre-spieser Great, thank you, could you aloso create a new release for AspNetCore.Identity.MongoDbCore targeting MongoDB Driver 2.28.0?

**Comment by alexandre-spieser** [comment]
Yup, just I've done it here https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/releases/tag/6.0.0

**Pull request closed without merging**
